resources:
  repositories:
  - repository: templates
    type: github
    name: JFolberth/TheYAMLPipelineOne
    endpoint: JFolberth
    ref: feature/synapse

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: 'workspaceName'
    type: string
    default: 'sy-synapsecicd-dev-eus'


stages:
  - template: stages/synapse_build_stage.yml@templates
    parameters:
      TargetWorkspaceName: ${{ parameters.workspaceName }}

